<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>MathVerse</RootNamespace>
    <AssemblyName>MathVerse.Kernel</AssemblyName>
    <Description>MathVerse core primitives and abstractions</Description>
    <PackageId>MathVerse.Kernel</PackageId>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" />
    <PackageReference Include="System.IO.Pipelines" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>

</Project>
