namespace MathVerse.Math.Compiler.CodeGen;

using System;
using System.Collections.Generic;
using System.Text;
using MathVerse.Math.Compiler.IR;

/// <summary>
/// Generates C# code from IR. Maps IROpCode values to C# operators and System.Math functions.
/// </summary>
public sealed class CSharpGenerator : CodeGenerator
{
    /// <inheritdoc/>
    public override string Generate(IRModule module)
    {
        var sb = new StringBuilder(2048);
        sb.AppendLine("// Generated by MathVerse Compiler");
        sb.AppendLine("using System;");
        sb.AppendLine();

        for (var i = 0; i < module.Functions.Count; i++)
        {
            if (i > 0) sb.AppendLine();
            sb.Append(GenerateFunction(module.Functions[i]));
        }

        return sb.ToString();
    }

    /// <inheritdoc/>
    public override string GenerateFunction(IRFunction function)
    {
        var sb = new StringBuilder(1024);
        var returnType = MapType(function.ReturnType);

        sb.Append($"public static {returnType} {KernelGenerator.SanitizeName(function.Name)}(");
        EmitParameterList(sb, function);
        sb.AppendLine(")");
        sb.AppendLine("{");

        EmitLocalDeclarations(sb, function);
        EmitBody(sb, function);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitParameterList(StringBuilder sb, IRFunction function)
    {
        for (var i = 0; i < function.Parameters.Count; i++)
        {
            if (i > 0) sb.Append(", ");
            var p = function.Parameters[i];
            sb.Append($"{MapType(p.Type)} {KernelGenerator.SanitizeName(p.Name)}");
        }
    }

    private static void EmitLocalDeclarations(StringBuilder sb, IRFunction function)
    {
        var declared = new HashSet<int>();
        for (var i = 0; i < function.Parameters.Count; i++)
            declared.Add(function.Parameters[i].Id);

        for (var b = 0; b < function.Blocks.Count; b++)
        {
            var block = function.Blocks[b];
            for (var j = 0; j < block.Instructions.Count; j++)
            {
                var inst = block.Instructions[j];
                if (inst.Result != null && declared.Add(inst.Result.Id))
                {
                    sb.AppendLine($"    {MapType(inst.Result.Type)} {KernelGenerator.SanitizeName(inst.Result.Name)};");
                }
            }
        }
    }

    private static void EmitBody(StringBuilder sb, IRFunction function)
    {
        var needsLabels = function.Blocks.Count > 1;

        for (var b = 0; b < function.Blocks.Count; b++)
        {
            var block = function.Blocks[b];

            if (needsLabels)
                sb.AppendLine($"    // Block: {block.Label}");

            for (var j = 0; j < block.Instructions.Count; j++)
            {
                EmitInstruction(sb, block.Instructions[j], function);
            }

            if (block.Terminator != null && !block.Instructions.Contains(block.Terminator))
            {
                EmitInstruction(sb, block.Terminator, function);
            }
        }
    }

    private static void EmitInstruction(StringBuilder sb, IRInstruction inst, IRFunction function)
    {
        switch (inst.OpCode)
        {
            case IROpCode.Add:
            case IROpCode.Sub:
            case IROpCode.Mul:
            case IROpCode.Div:
            case IROpCode.Mod:
                EmitBinaryOp(sb, inst);
                break;
            case IROpCode.Neg:
                EmitUnaryOp(sb, inst, "-");
                break;
            case IROpCode.Abs:
                EmitMathCall(sb, inst, "System.Math.Abs");
                break;
            case IROpCode.Sqrt:
                EmitMathCall(sb, inst, "System.Math.Sqrt");
                break;
            case IROpCode.Sin:
                EmitMathCall(sb, inst, "System.Math.Sin");
                break;
            case IROpCode.Cos:
                EmitMathCall(sb, inst, "System.Math.Cos");
                break;
            case IROpCode.Tan:
                EmitMathCall(sb, inst, "System.Math.Tan");
                break;
            case IROpCode.Log:
                EmitMathCall(sb, inst, "System.Math.Log");
                break;
            case IROpCode.Exp:
                EmitMathCall(sb, inst, "System.Math.Exp");
                break;
            case IROpCode.Pow:
                EmitMathCall(sb, inst, "System.Math.Pow");
                break;
            case IROpCode.Fma:
                EmitFma(sb, inst);
                break;
            case IROpCode.Load:
                EmitLoad(sb, inst);
                break;
            case IROpCode.Store:
                EmitStore(sb, inst);
                break;
            case IROpCode.Branch:
                EmitBranch(sb, inst, function);
                break;
            case IROpCode.CondBranch:
                EmitCondBranch(sb, inst, function);
                break;
            case IROpCode.Return:
                EmitReturn(sb, inst);
                break;
            case IROpCode.Call:
                EmitCall(sb, inst);
                break;
            case IROpCode.Cast:
                EmitCast(sb, inst);
                break;
            case IROpCode.Dot:
                EmitMathCall(sb, inst, "System.Numerics.Vector.Dot");
                break;
            case IROpCode.Phi:
                EmitPhiComment(sb, inst);
                break;
            case IROpCode.Nop:
                break;
            case IROpCode.Alloc:
                EmitAlloc(sb, inst);
                break;
            default:
                sb.AppendLine($"    // Unsupported: {inst.OpCode}");
                break;
        }
    }

    private static void EmitBinaryOp(StringBuilder sb, IRInstruction inst)
    {
        var op = inst.OpCode switch
        {
            IROpCode.Add => "+",
            IROpCode.Sub => "-",
            IROpCode.Mul => "*",
            IROpCode.Div => "/",
            IROpCode.Mod => "%",
            _ => "+"
        };

        sb.Append("    ");
        if (inst.Result != null)
            sb.Append($"{KernelGenerator.SanitizeName(inst.Result.Name)} = ");
        sb.AppendLine($"{KernelGenerator.FormatOp(inst.Operands[0])} {op} {KernelGenerator.FormatOp(inst.Operands[1])};");
    }

    private static void EmitUnaryOp(StringBuilder sb, IRInstruction inst, string op)
    {
        sb.Append("    ");
        if (inst.Result != null)
            sb.Append($"{KernelGenerator.SanitizeName(inst.Result.Name)} = ");
        sb.AppendLine($"{op}{KernelGenerator.FormatOp(inst.Operands[0])};");
    }

    private static void EmitMathCall(StringBuilder sb, IRInstruction inst, string funcName)
    {
        sb.Append("    ");
        if (inst.Result != null)
            sb.Append($"{KernelGenerator.SanitizeName(inst.Result.Name)} = ");
        sb.Append($"{funcName}(");
        for (var i = 0; i < inst.Operands.Count; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(KernelGenerator.FormatOp(inst.Operands[i]));
        }
        sb.AppendLine(");");
    }

    private static void EmitFma(StringBuilder sb, IRInstruction inst)
    {
        sb.Append("    ");
        if (inst.Result != null)
            sb.Append($"{KernelGenerator.SanitizeName(inst.Result.Name)} = ");
        sb.AppendLine($"{KernelGenerator.FormatOp(inst.Operands[0])} * {KernelGenerator.FormatOp(inst.Operands[1])} + {KernelGenerator.FormatOp(inst.Operands[2])};");
    }

    private static void EmitLoad(StringBuilder sb, IRInstruction inst)
    {
        sb.Append("    ");
        if (inst.Result != null)
            sb.Append($"{KernelGenerator.SanitizeName(inst.Result.Name)} = ");
        sb.AppendLine($"{KernelGenerator.FormatOp(inst.Operands[0])};");
    }

    private static void EmitStore(StringBuilder sb, IRInstruction inst)
    {
        sb.AppendLine($"    {KernelGenerator.FormatOp(inst.Operands[0])} = {KernelGenerator.FormatOp(inst.Operands[1])};");
    }

    private static void EmitBranch(StringBuilder sb, IRInstruction inst, IRFunction function)
    {
        var label = FindTargetLabel(inst, inst.Operands.Count - 1, function);
        sb.AppendLine($"    goto {KernelGenerator.SanitizeName(label)};");
    }

    private static void EmitCondBranch(StringBuilder sb, IRInstruction inst, IRFunction function)
    {
        if (inst.Operands.Count < 2)
        {
            sb.AppendLine("    // malformed conditional branch");
            return;
        }

        var cond = KernelGenerator.FormatOp(inst.Operands[0]);
        var trueLabel = FindTargetLabel(inst, 1, function);
        sb.AppendLine($"    if ({cond}) goto {KernelGenerator.SanitizeName(trueLabel)};");

        if (inst.Operands.Count >= 3)
        {
            var falseLabel = FindTargetLabel(inst, 2, function);
            sb.AppendLine($"    goto {KernelGenerator.SanitizeName(falseLabel)};");
        }
    }

    private static void EmitReturn(StringBuilder sb, IRInstruction inst)
    {
        if (inst.Operands.Count > 0)
            sb.AppendLine($"    return {KernelGenerator.FormatOp(inst.Operands[0])};");
        else
            sb.AppendLine("    return;");
    }

    private static void EmitCall(StringBuilder sb, IRInstruction inst)
    {
        sb.Append("    ");
        if (inst.Result != null)
            sb.Append($"{KernelGenerator.SanitizeName(inst.Result.Name)} = ");

        var callee = inst.Operands.Count > 0 ? KernelGenerator.FormatOp(inst.Operands[0]) : "Unknown";
        sb.Append($"{callee}(");
        for (var i = 1; i < inst.Operands.Count; i++)
        {
            if (i > 1) sb.Append(", ");
            sb.Append(KernelGenerator.FormatOp(inst.Operands[i]));
        }
        sb.AppendLine(");");
    }

    private static void EmitCast(StringBuilder sb, IRInstruction inst)
    {
        var targetType = MapType(inst.Result?.Type ?? IRType.Float64);
        sb.Append("    ");
        if (inst.Result != null)
            sb.Append($"{KernelGenerator.SanitizeName(inst.Result.Name)} = ");
        sb.AppendLine($"({targetType}){KernelGenerator.FormatOp(inst.Operands[0])};");
    }

    private static void EmitPhiComment(StringBuilder sb, IRInstruction inst)
    {
        sb.AppendLine($"    // phi: {inst.Result?.Name ?? "?"} (requires SSA destruction before C# emission)");
    }

    private static void EmitAlloc(StringBuilder sb, IRInstruction inst)
    {
        if (inst.Result != null)
        {
            var type = MapType(inst.Result.Type);
            sb.AppendLine($"    {type}[] {KernelGenerator.SanitizeName(inst.Result.Name)} = new {type}[{KernelGenerator.FormatOp(inst.Operands[0])}];");
        }
    }

    private static string FindTargetLabel(IRInstruction inst, int operandIndex, IRFunction function)
    {
        if (operandIndex < 0 || operandIndex >= inst.Operands.Count)
            return "unknown";

        var operand = inst.Operands[operandIndex];

        for (var i = 0; i < function.Blocks.Count; i++)
        {
            var b = function.Blocks[i];
            if (b.Label == operand.Name || b.Label.EndsWith("." + operand.Name))
                return b.Label;
        }

        return operand.Name;
    }

    internal static string MapType(IRType type)
    {
        return type switch
        {
            IRType.Float32 => "float",
            IRType.Float64 => "double",
            IRType.Int32 => "int",
            IRType.Int64 => "long",
            IRType.Bool => "bool",
            IRType.Void => "void",
            IRType.Pointer => "IntPtr",
            IRType.Vector => "System.Numerics.Vector<double>",
            IRType.Tensor => "double[]",
            _ => "object"
        };
    }
}
