<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>MathVerse.Math.Parsing</RootNamespace>
    <AssemblyName>MathVerse.Math.Parsing</AssemblyName>
    <Description>MathVerse mathematical expression parser</Description>
    <PackageId>MathVerse.Math.Parsing</PackageId>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\MathVerse.Math.Core.csproj" />
    <ProjectReference Include="..\..\Kernel\MathVerse.Kernel.csproj" />
  </ItemGroup>

</Project>
