<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <RootNamespace>MathVerse.Semantics.Tests</RootNamespace>
    <AssemblyName>MathVerse.Semantics.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Math\Semantics\MathVerse.Math.Semantics.csproj" />
    <ProjectReference Include="..\..\src\Math\Parsing\MathVerse.Math.Parsing.csproj" />
    <ProjectReference Include="..\..\src\Kernel\MathVerse.Kernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

</Project>
