<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>MathVerse.Math.Statistics</RootNamespace>
    <AssemblyName>MathVerse.Math.Statistics</AssemblyName>
    <Description>MathVerse statistical methods</Description>
    <PackageId>MathVerse.Math.Statistics</PackageId>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\MathVerse.Math.Core.csproj" />
    <ProjectReference Include="..\Numerical\MathVerse.Math.Numerical.csproj" />
    <ProjectReference Include="..\..\Kernel\MathVerse.Kernel.csproj" />
  </ItemGroup>

</Project>
